[[redirects]]
  from = "/*"
  to = "/"
  status = 200
[build]
  command = "npm run build"
  publish = ".next"
[functions]
  node_bundler = "esbuild"
  external_node_modules = [ "@ampproject/toolbox-optimizer", "sharp"]